### ISSUE TITLE
Does not compile (Arduino v1.6.4)

### ISSUE THREAD

**Issue by Andon-A** [cpldcpu/uTFT-ST7735#1]
Trying to get this working for an ATTiny84 running a 1.8" TFT using the ST7735 driver.

This is what I get when I try to compile the example, or even just #include <uTFT_ST7735.h>

I'll freely admit I don't know enough about this to figure out why it's not working.

In file included from sketch_jun03b.ino:1:0:
D:\Users\Andon\Documents\Arduino\libraries\uTFT_ST7735/uTFT_ST7735.h:59:6: error: previous declaration of 'void init()' with 'C++' linkage
 void init(void);
      ^
In file included from sketch_jun03b.ino:3:0:
D:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino/Arduino.h:120:15: error: conflicts with new declaration with 'C' linkage
 void init(void);
               ^
Error compiling

**Comment by cpldcpu** [comment]
Actually this library is not an Arduino library. You can use Adafruits original library if you need Arduino support.
