### ISSUE TITLE
More text sizes

### ISSUE THREAD

**Issue by jaskamakkara** [cpldcpu/uTFT-ST7735#5]
Hi, I am looking for a very lightweight ST7735 library for Arduino and this seems to fit the bill. Unfortnately I'd still like the ability to use larger fonts (all I need the library for is printing some numbers to the screen in big font). Can this change be implemented easily? Thanks for any help.

**Comment by cpldcpu** [comment]
You could simply render the same font in a 2x zoomed up version. Should not be too difficult.

**Comment by jaskamakkara** [comment]
So do you mean defining larger characters in the font file?

**Comment by cpldcpu** [comment]
Just change the render code to duplicate pixel size.

**Comment by jaskamakkara** [comment]
OK, I'll give it a go. Thanks
